export const CNP_CODES = [
  "00010 Membres des corps législatifs",
  "00011 Cadres supérieurs/cadres supérieures - administration publique",
  "00012 Cadres supérieurs/cadres supérieures - services financiers, communications et autres services aux entreprises",
  "00013 Cadres supérieurs/cadres supérieures - santé, enseignement, services sociaux et communautaires et associations mutuelles",
  "00014 Cadres supérieurs/cadres supérieures - commerce, radiotélédiffusion et autres services",
  "00015 Cadres supérieurs/cadres supérieures - construction, transport, production et services d'utilité publique",
  "10010 Directeurs financiers/directrices financières",
  "10011 Directeurs/directrices des ressources humaines",
  "10012 Directeurs/directrices des achats",
  "10019 Directeurs/directrices d'autres services administratifs",
  "10020 Directeurs/directrices des assurances, de l'immobilier et du courtage financier",
  "10021 Directeurs/directrices de banque, du crédit et d'autres services de placements",
  "10022 Directeurs/directrices de la publicité, du marketing et des relations publiques",
  "10029 Directeurs/directrices d'autres services aux entreprises",
  "10030 Directeurs/directrices d'entreprises de télécommunications",
  "11100 Vérificateurs/vérificatrices et comptables",
  "11101 Analystes financiers/analystes financières et analystes en placements",
  "11102 Conseillers financiers/conseillères financières",
  "11103 Agents/agentes en valeurs, agents/agentes en placements et négociateurs/négociatrices en valeurs",
  "11109 Autres agents financiers/agentes financières",
  "11200 Professionnels/professionnelles en ressources humaines",
  "11201 Professionnels/professionnelles des services-conseils en gestion aux entreprises",
  "11202 Professionnels/professionnelles en publicité, en marketing et en relations publiques",
  "12010 Superviseurs/superviseures de commis de bureau et du personnel de soutien administratif",
  "12011 Superviseurs/superviseures de commis de finance et d'assurance",
  "12012 Superviseurs/superviseures de commis de bibliothèque, de correspondanciers et d'autres commis à l'information",
  "12013 Superviseurs/superviseures du personnel de coordination de la chaîne d'approvisionnement, du suivi et des horaires",
  "12100 Adjoints/adjointes de direction",
  "12101 Agents/agentes des ressources humaines et de recrutement",
  "12102 Agents/agentes en approvisionnement et aux achats",
  "12103 Planificateurs/planificatrices de congrès et d'événements",
  "12104 Agents/agentes d'assurance-emploi et du revenu",
  "12110 Sténographes judiciaires, transcripteurs médicaux/transcriptrices médicales et personnel assimilé",
  "12111 Personnel en gestion de l'information sur la santé",
  "12112 Techniciens/techniciennes à la gestion des documents",
  "12113 Agents/agentes de statistiques et professions connexes du soutien de la recherche",
  "12200 Techniciens/techniciennes en comptabilité et teneurs/teneuses de livres",
  "12201 Experts/expertes en sinistres et rédacteurs/rédactrices sinistres",
  "12202 Assureurs/assureures",
  "12203 Estimateurs/estimatrices, évaluateurs/évaluatrices d'entreprise et autres évaluateurs/évaluatrices",
  "13100 Agents/agentes d'administration",
  "13101 Agents/agentes de gestion immobilière",
  "13102 Administrateurs/administratrices de la paye",
  "13110 Adjoints administratifs/adjointes administratives",
  "13111 Adjoints administratifs juridiques/adjointes administratives juridiques",
  "13112 Adjoints administratifs médicaux/adjointes administratives médicales",
  "13200 Courtiers/courtières en douanes, courtiers maritimes/courtières maritimes et autres courtiers/courtières",
  "13201 Coordonnateurs/coordonnatrices de la logistique de la production et du transport",
  "14100 Employés/employées de bureau - soutien général",
  "14101 Réceptionnistes",
  "14102 Commis des services du personnel",
  "14103 Commis des services judiciaires et autres professions des services judiciaires",
  "14110 Intervieweurs/intervieweuses pour enqu├¬tes et commis aux statistiques",
  "14111 Commis à la saisie de données",
  "14112 Opérateurs/opératrices d'équipement d'éditique et personnel assimilé",
  "14200 Commis à la comptabilité et personnel assimilé",
  "14201 Commis de banque, d'assurance et d'autres services financiers",
  "14202 Commis de recouvrement",
  "14300 Commis et assistants/assistantes dans les bibliothèques",
  "14301 Correspondanciers/correspondancières et commis aux publications et aux règlements",
  "14400 Expéditeurs/expéditrices et réceptionnaires",
  "14401 Magasiniers/magasinières et commis aux pièces",
  "14402 Travailleurs/travailleuses de la logistique de la production",
  "14403 Commis aux achats et au contrôle de l'inventaire",
  "14404 Répartiteurs/répartitrices",
  "14405 Horairistes de trajets et d'équipages",
  "20010 Directeurs/directrices des services de génie",
  "20011 Directeurs/directrices des services d'architecture et de sciences",
  "20012 Gestionnaires des systèmes informatiques",
  "21100 Physiciens/physiciennes et astronomes",
  "21101 Chimistes",
  "21102 Géoscientifiques et océanographes",
  "21103 Météorologues et climatologues",
  "21109 Autres professionnels/professionnelles des sciences physiques",
  "21110 Biologistes et personnel scientifique assimilé",
  "21111 Professionnels/professionnelles des sciences forestières",
  "21112 Agronomes, conseillers/conseillères et spécialistes en agriculture",
  "21120 Professionnels/professionnelles de la santé et sécurité publique et environnementale",
  "21200 Architectes",
  "21201 Architectes paysagistes",
  "21202 Urbanistes et planificateurs/planificatrices de l'utilisation des sols",
  "21203 Arpenteurs-géomètres/arpenteuses-géomètres",
  "21210 Mathématiciens/mathématiciennes, statisticiens/statisticiennes et actuaires",
  "21211 Scientifiques des données",
  "21220 Spécialistes de la cybersécurité",
  "21221 Spécialistes des systèmes commerciaux",
  "21222 Spécialistes en informatique",
  "21223 Analystes de bases de données et administrateurs/administratrices de données",
  "21230 Développeurs/développeuses et programmeurs/programmeuses de systèmes informatiques",
  "21231 Ingénieurs/ingénieures et concepteurs/conceptrices en logiciel",
  "21232 Développeurs/développeuses et programmeurs/programmeuses de logiciels",
  "21233 Concepteurs/conceptrices Web",
  "21234 Développeurs/développeuses et programmeurs/programmeuses Web",
  "21300 Ingénieurs civils/ingénieures civiles",
  "21301 Ingénieurs mécaniciens/ingénieures mécaniciennes",
  "21310 Ingénieurs électriciens et électroniciens/ingénieures électriciennes et électroniciennes",
  "21311 Ingénieurs informaticiens/ingénieures informaticiennes (sauf ingénieurs/ingénieures et concepteurs/conceptrices en logiciel)",
  "21320 Ingénieurs chimistes/ingénieures chimistes",
  "21321 Ingénieurs/ingénieures d'industrie et de fabrication",
  "21322 Ingénieurs/ingénieures métallurgistes et des matériaux",
  "21330 Ingénieurs miniers/ingénieures minières",
  "21331 Ingénieurs/ingénieures géologiques",
  "21332 Ingénieurs/ingénieures de l'extraction et du raffinage du pétrole",
  "21390 Ingénieurs/ingénieures en aérospatiale",
  "21399 Autres ingénieurs/ingénieures",
  "22100 Technologues et techniciens/techniciennes en chimie",
  "22101 Technologues et techniciens/techniciennes en géologie et en minéralogie",
  "22110 Technologues et techniciens/techniciennes en biologie",
  "22111 Inspecteurs/inspectrices des produits agricoles et de la p├¬che",
  "22112 Technologues et techniciens/techniciennes en sciences forestières",
  "22113 Techniciens/techniciennes du milieu naturel et de la p├¬che",
  "22114 Techniciens/techniciennes et spécialistes de l'aménagement paysager et de l'horticulture",
  "22210 Technologues et techniciens/techniciennes en architecture",
  "22211 Designers industriels/designers industrielles",
  "22212 Technologues et techniciens/techniciennes en dessin",
  "22213 Technologues et techniciens/techniciennes en arpentage",
  "22214 Personnel technique en géomatique et en météorologie",
  "22220 Techniciens/techniciennes de réseau informatique et Web",
  "22221 Agents/agentes de soutien aux utilisateurs",
  "22222 ├ëvaluateurs/évaluatrices de systèmes informatiques",
  "22230 Vérificateurs/vérificatrices et inspecteurs/inspectrices des essais non destructifs",
  "22231 Inspecteurs/inspectrices d'ingénierie et officiers/officières de réglementation",
  "22232 Spécialistes de l'hygiène et de la sécurité au travail",
  "22233 Inspecteurs/inspectrices en construction",
  "22300 Technologues et techniciens/techniciennes en génie civil",
  "22301 Technologues et techniciens/techniciennes en génie mécanique",
  "22302 Technologues et techniciens/techniciennes en génie industriel et en génie de fabrication",
  "22303 Estimateurs/estimatrices en construction",
  "22310 Technologues et techniciens/techniciennes en génie électrique et électronique",
  "22311 ├ëlectroniciens/électroniciennes d'entretien (biens domestiques et commerciaux)",
  "22312 Techniciens/techniciennes et mécaniciens/mécaniciennes d'instruments industriels",
  "22313 Mécaniciens/mécaniciennes, techniciens/techniciennes et contrôleurs/contrôleuses d'avionique et d'instruments et d'appareillages électriques d'aéronefs",
  "30010 Directeurs/directrices des soins de santé",
  "31100 Spécialistes en médecine clinique et de laboratoire",
  "31101 Spécialistes en chirurgie",
  "31102 Omnipraticiens/omnipraticiennes et médecins en médecine familiale",
  "31103 Vétérinaires",
  "31110 Dentistes",
  "31111 Optométristes",
  "31112 Audiologistes et orthophonistes",
  "31120 Pharmaciens/pharmaciennes",
  "31121 Diététistes et nutritionnistes",
  "31200 Psychologues",
  "31201 Chiropraticiens/chiropraticiennes",
  "31202 Physiothérapeutes",
  "31203 Ergothérapeutes",
  "31204 Kinésiologues et autres professionnels/professionnelles en thérapie et en diagnostic",
  "31209 Autres professionnels/professionnelles en diagnostic et en traitement de la santé",
  "31300 Coordonnateurs/coordonnatrices et superviseurs/superviseures des soins infirmiers",
  "31301 Infirmiers autorisés/infirmières autorisées et infirmiers psychiatriques autorisés/infirmières psychiatriques autorisées",
  "31302 Infirmiers praticiens/infirmières praticiennes",
  "31303 Adjoints au médecin, sages-femmes et professionnels paramédicaux",
  "32100 Opticiens/opticiennes d'ordonnances",
  "32101 Infirmiers auxiliaires/infirmières auxiliaires",
  "32102 Personnel ambulancier et paramédical",
  "32103 Inhalothérapeutes, perfusionnistes cardiovasculaires et technologues cardiopulmonaires",
  "32104 Technologues en santé animale et techniciens/techniciennes vétérinaires",
  "32109 Autre personnel technique en thérapie et en diagnostic",
  "32110 Denturologistes",
  "32111 Hygiénistes et thérapeutes dentaires",
  "32112 Technologues et techniciens/techniciennes dentaires",
  "32120 Technologues de laboratoires médicaux",
  "32121 Technologues en radiation médicale",
  "32122 Technologues en échographie",
  "32123 Technologues en cardiologie et technologues en électrophysiologie diagnostique",
  "32124 Techniciens/techniciennes en pharmacie",
  "32129 Autres technologues et techniciens/techniciennes des sciences de la santé",
  "32200 Praticiens/praticiennes en médecine traditionnelle chinoise et acupuncteurs/acupunctrices",
  "32201 Massothérapeutes",
  "32209 Autres praticiens/praticiennes des médecines douces",
  "33100 Assistants/assistantes dentaires et auxiliaires dans les laboratoires dentaires",
  "33101 Assistants/assistantes de laboratoires médicaux et professions techniques connexes",
  "33102 Aides-infirmiers/aides-infirmières, aides-soignants/aides-soignantes et préposés/préposées aux bénéficiaires",
  "33103 Assistants techniques/assistantes techniques en pharmacie et assistants/assistantes en pharmacie",
  "33109 Autre personnel de soutien des services de santé",
  "40010 Gestionnaires de la fonction publique - élaboration de politiques et administration de programmes sociaux et de santé",
  "40011 Gestionnaires de la fonction publique - analyse économique, élaboration de politiques et administration de programmes",
  "40012 Gestionnaires de la fonction publique - élaboration de politiques en matière d'éducation et administration de programmes",
  "40019 Autres gestionnaires de la fonction publique",
  "40020 Administrateurs/administratrices - enseignement postsecondaire et formation professionnelle",
  "40021 Directeurs/directrices d'école et administrateurs/administratrices de programmes d'enseignement aux niveaux primaire et secondaire",
  "40030 Directeurs/directrices des services sociaux, communautaires et correctionnels",
  "40040 Officiers/officières de direction des services de police et professions connexes des services de la protection du public",
  "40041 Chefs et officiers supérieurs/officières supérieures des services d'incendie",
  "40042 Officiers/officières de direction des Forces armées canadiennes",
  "41100 Juges",
  "41101 Avocats/avocates (partout au Canada) et notaires (au Québec)",
  "41200 Professeurs/professeures et chargés/chargées de cours au niveau universitaire",
  "41201 Assistants/assistantes d'enseignement et de recherche au niveau postsecondaire",
  "41210 Enseignants/enseignantes au niveau collégial et autres instructeurs/instructrices en formation professionnelle",
  "41220 Enseignants/enseignantes au niveau secondaire",
  "41221 Enseignants/enseignantes aux niveaux primaire et préscolaire",
  "41300 Travailleurs sociaux/travailleuses sociales",
  "41301 Thérapeutes en counseling et thérapies spécialisées connexes",
  "41302 Chefs religieux",
  "41310 Enqu├¬teurs/enqu├¬teuses de police et autres professions d'enqu├¬te",
  "41311 Agents/agentes de probation et de libération conditionnelle",
  "41320 Conseillers/conseillères en information scolaire",
  "41321 Conseillers/conseillères en développement de carrière et conseillers/conseillères en orientation (sauf éducation)",
  "41400 Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes, en sciences naturelles et appliquées",
  "41401 ├ëconomistes, recherchistes et analystes des politiques économiques",
  "41402 Agents/agentes de développement économique et recherchistes et analystes en marketing",
  "41403 Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes en politiques sociales",
  "41404 Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes en politiques de la santé",
  "41405 Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes en politiques de l'enseignement",
  "41406 Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programme en sports, en loisirs et en conditionnement physique",
  "41407 Agents/agentes de programmes propres au gouvernement",
  "41409 Autres professionnels/professionnelles des sciences sociales",
  "42100 Policiers/policières (sauf cadres supérieurs)",
  "42101 Pompiers/pompières",
  "42102 Membres spécialisés des Forces armées canadiennes",
  "42200 Techniciens/techniciennes juridiques et personnel assimilé",
  "42201 Travailleurs/travailleuses des services sociaux et communautaires",
  "42202 ├ëducateurs/éducatrices et aides-éducateurs/aides-éducatrices de la petite enfance",
  "42203 Instructeurs/instructrices pour personnes ayant une déficience",
  "42204 Travailleurs/travailleuses de la religion",
  "43100 Aides-enseignants/aides-enseignantes aux niveaux primaire et secondaire",
  "43109 Autres instructeurs/instructrices",
  "43200 Shérifs et huissiers/huissières de justice",
  "43201 Agents/agentes de services correctionnels",
  "43202 Agents/agentes d'application de règlements municipaux et autres agents/agentes de réglementation",
  "43203 Agents/agentes de services frontaliers, des douanes et de l'immigration",
  "43204 Membres des opérations des Forces armées canadiennes",
  "44100 Gardiens/gardiennes d'enfants en milieu familial",
  "44101 Aides de maintien à domicile, aides familiaux/familiales et personnel assimilé",
  "44200 Combattants de première ligne des Forces armées canadiennes",
  "45100 Surveillants/surveillantes d'élèves, brigadiers/brigadières et autres professions connexes",
  "50010 Directeurs/directrices de bibliothèques, des archives, de musées et de galeries d'art",
  "50011 Directeurs/directrices - édition, cinéma, radiotélédiffusion et arts de la scène",
  "50012 Directeurs/directrices de programmes et de services de sports, de loisirs et de conditionnement physique",
  "51100 Bibliothécaires",
  "51101 Restaurateurs/restauratrices et conservateurs/conservatrices",
  "51102 Archivistes",
  "51110 Réviseurs/réviseures, rédacteurs-réviseurs/rédactrices-réviseures et chefs du service des nouvelles",
  "51111 Auteurs/auteures, écrivains/écrivaines et rédacteurs/rédactrices (sauf techniques)",
  "51112 Rédacteurs/rédactrices techniques",
  "51113 Journalistes",
  "51114 Traducteurs/traductrices, terminologues et interprètes",
  "51120 Producteurs/productrices, réalisateurs/réalisatrices, chorégraphes et personnel assimilé",
  "51121 Chefs d'orchestre, compositeurs/compositrices et arrangeurs/arrangeuses",
  "51122 Musiciens/musiciennes et chanteurs/chanteuses",
  "52100 Techniciens/techniciennes dans les bibliothèques et les services d'archives publiques",
  "52110 Cadreurs/cadreuses de films et cadreurs/cadreuses vidéo",
  "52111 Techniciens/techniciennes en graphisme",
  "52112 Techniciens/techniciennes en radiotélédiffusion",
  "52113 Techniciens/techniciennes en enregistrement audio et vidéo",
  "52114 Annonceurs/annonceuses et autres communicateurs/communicatrices",
  "52119 Autre personnel technique et personnel de coordination du cinéma, de la radiotélédiffusion et des arts de la scène",
  "52120 Designers graphiques et illustrateurs/illustratrices",
  "52121 Designers d'intérieur et décorateurs/décoratrices d'intérieur",
  "53100 Registraires, restaurateurs/restauratrices, interprètes et autres travailleurs/travailleuses dans les domaines apparentés des musées et des galeries d'art",
  "53110 Photographes",
  "53111 Assistants/assistantes et opérateurs/opératrices du domaine du cinéma, de la radiotélédiffusion, de la photographie et des arts de la scène",
  "53120 Danseurs/danseuses",
  "53121 Acteurs/actrices, comédiens/comédiennes et artistes de cirque",
  "53122 Peintres, sculpteurs/sculpteures et autres artistes des arts visuels",
  "53123 Ensembliers/ensemblières de théâtre, dessinateurs/dessinatrices de mode, concepteurs/conceptrices d'expositions et autres concepteurs/conceptrices artistiques",
  "53124 Artisans/artisanes",
  "53125 Patronniers/patronnières de produits textiles et d'articles en cuir et en fourrure",
  "53200 Athlètes",
  "53201 Entraîneurs/entraîneuses",
  "53202 Arbitres et officiels/officielles de sports",
  "54100 Animateurs/animatrices et responsables de programmes de sports, de loisirs et de conditionnement physique",
  "55109 Autres artistes de spectacle",
  "60010 Directeurs/directrices des ventes corporatives",
  "60020 Directeurs/directrices - commerce de détail et de gros",
  "60030 Directeurs/directrices de la restauration et des services alimentaires",
  "60031 Directeurs/directrices des services d'hébergement",
  "60040 Directeurs/directrices du service à la clientèle et des services personnels",
  "62010 Superviseurs/superviseures des ventes - commerce de détail",
  "62020 Superviseurs/superviseures des services alimentaires",
  "62021 Gouvernants principaux/gouvernantes principales",
  "62022 Superviseurs/superviseures des services d'hébergement, de voyages, de tourisme et des services connexes",
  "62023 Superviseurs/superviseures des services d'information et des services à la clientèle",
  "62024 Surveillants/surveillantes des services de nettoyage",
  "62029 Surveillants/surveillantes des autres services",
  "62100 Spécialistes des ventes techniques - commerce de gros",
  "62101 Acheteurs/acheteuses des commerces de détail et de gros",
  "62200 Chefs",
  "62201 Directeurs/directrices de funérailles et embaumeurs/embaumeuses",
  "62202 Bijoutiers/bijoutières, réparateurs/réparatrices de bijoux, horlogers-rhabilleurs/horlogères-rhabilleuses et personnel assimilé",
  "63100 Agents/agentes et courtiers/courtières d'assurance",
  "63101 Agents/agentes et vendeurs/vendeuses en immobilier",
  "63102 Représentants/représentantes des ventes financières",
  "63200 Cuisiniers/cuisinières",
  "63201 Bouchers/bouchères - commerce de gros et de détail",
  "63202 Boulangers-pâtissiers/boulangères-pâtissières",
  "63210 Coiffeurs/coiffeuses et barbiers",
  "63211 Esthéticiens/esthéticiennes, électrolystes et personnel assimilé",
  "63220 Cordonniers/cordonnières et fabricants/fabricantes de chaussures",
  "63221 Tapissiers-garnisseurs/tapissières-garnisseuses",
  "64100 Vendeurs/vendeuses et décorateurs-étalagistes/décoratrices-étalagistes en commerce de détail",
  "64101 Représentants/représentantes des ventes et des comptes - commerce de gros (non-technique)",
  "64200 Tailleurs/tailleuses, couturiers/couturières, fourreurs/fourreuses et modistes",
  "64201 Conseillers/conseillères imagistes, conseillers mondains/conseillères mondaines et autres conseillers/conseillères en soins personnalisés",
  "64300 Maîtres d'hôtel et hôtes/hôtesses",
  "64301 Barmans/barmaids",
  "64310 Conseillers/conseillères en voyages",
  "64311 Commissaires et agents/agentes de bord",
  "64312 Agents/agentes à la billetterie et aux services aériens",
  "64313 Agents/agentes à la billetterie, représentants/représentantes du service en matière de fret et personnel assimilé dans le transport routier et maritime",
  "64314 Réceptionnistes d'hôtel",
  "64320 Guides touristiques et guides itinérants/guides itinérantes",
  "64321 Travailleurs/travailleuses dans les casinos",
  "64322 Guides d'activités récréatives et sportives de plein air",
  "64400 Représentants/représentantes au service à la clientèle - institutions financières",
  "64401 Représentants/représentantes des services postaux",
  "64409 Autres préposés/préposées aux services d'information et aux services à la clientèle",
  "64410 Agents/agentes de sécurité et personnel assimilé des services de sécurité",
  "65100 Caissiers/caissières",
  "65101 Préposés/préposées de stations-service",
  "65102 Garnisseurs/garnisseuses de tablettes, commis et préposés/préposées aux commandes dans les magasins",
  "65109 Autre personnel assimilé des ventes",
  "65200 Serveurs/serveuses d'aliments et de boissons",
  "65201 Serveurs/serveuses au comptoir, aides de cuisine et personnel de soutien assimilé",
  "65202 Coupeurs/coupeuses de viande et poissonniers/poissonnières - commerce de gros et de détail",
  "65210 Personnel de soutien en services d'hébergement, de voyage et en services de montage d'installation",
  "65211 Opérateurs/opératrices et préposés/préposées aux sports, aux loisirs et dans les parcs d'attractions",
  "65220 Soigneurs/soigneuses d'animaux et travailleurs/travailleuses en soins des animaux",
  "65229 Autres professions de soutien dans les services personnels",
  "65310 Préposés/préposées à l'entretien ménager et au nettoyage - travaux légers",
  "65311 Nettoyeurs spécialisés/nettoyeuses spécialisées",
  "65312 Concierges et nettoyeurs/nettoyeuses - gros travaux",
  "65320 Personnel de blanchisseries et d'établissements de nettoyage à sec et personnel assimilé",
  "65329 Autre personnel de soutien en service",
  "70010 Directeurs/directrices de la construction",
  "70011 Gestionnaires en construction et rénovation domiciliaire",
  "70012 Directeurs/directrices de l'exploitation et de l'entretien d'immeubles",
  "70020 Directeurs/directrices des transports",
  "70021 Directeurs/directrices des services postaux et de messageries",
  "72010 Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses des machinistes et du personnel des métiers du formage, du profilage et du montage des métaux et personnel assimilé",
  "72011 Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en électricité et en télécommunications",
  "72012 Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en tuyauterie",
  "72013 Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en charpenterie",
  "72014 Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses des autres métiers de la construction et des services de réparation et d'installation",
  "72020 Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en mécanique",
  "72021 Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses des équipes d'opérateurs d'équipement lourd",
  "72022 Surveillants/surveillantes de l'imprimerie et du personnel assimilé",
  "72023 Surveillants/surveillantes des opérations du transport ferroviaire",
  "72024 Surveillants/surveillantes du transport routier et du transport en commun",
  "72025 Superviseurs/superviseures de services postaux et de messageries",
  "72100 Machinistes et vérificateurs/vérificatrices d'usinage et d'outillage",
  "72101 Outilleurs-ajusteurs/outilleuses-ajusteuses",
  "72102 Tôliers/tôlières",
  "72103 Chaudronniers/chaudronnières",
  "72104 Assembleurs/assembleuses et ajusteurs/ajusteuses de plaques et de charpentes métalliques",
  "72105 Monteurs/monteuses de charpentes métalliques",
  "72106 Soudeurs/soudeuses et opérateurs/opératrices de machines à souder et à braser",
  "72200 ├ëlectriciens/électriciennes (sauf électriciens industriels/électriciennes industrielles et de réseaux électriques)",
  "72201 ├ëlectriciens industriels/électriciennes industrielles",
  "72202 ├ëlectriciens/électriciennes de réseaux électriques",
  "72203 Monteurs/monteuses de lignes électriques et de c├óbles",
  "72204 Installateurs/installatrices et réparateurs/réparatrices de lignes et de c├óbles de télécommunications",
  "72205 Techniciens/techniciennes en installation de matériel de télécommunication et en services de c├óblodistribution",
  "72300 Plombiers/plombières",
  "72301 Tuyauteurs/tuyauteuses, monteurs/monteuses d'appareils de chauffage et poseurs/poseuses de gicleurs",
  "72302 Monteurs/monteuses d'installations au gaz",
  "72310 Charpentiers-menuisiers/charpentières-menuisières",
  "72311 ├ëbénistes",
  "72320 Briqueteurs-ma├ºons/briqueteuses-ma├ºonnes",
  "72321 Calorifugeurs/calorifugeuses",
  "72400 Mécaniciens/mécaniciennes de chantier et mécaniciens industriels/mécaniciennes industrielles",
  "72401 Mécaniciens/mécaniciennes d'équipement lourd",
  "72402 Mécaniciens/mécaniciennes en chauffage, réfrigération et climatisation",
  "72403 Réparateurs/réparatrices de wagons",
  "72404 Mécaniciens/mécaniciennes et contrôleurs/contrôleuses d'aéronefs",
  "72405 Ajusteurs/ajusteuses de machines",
  "72406 Constructeurs/constructrices et mécaniciens/mécaniciennes d'ascenseurs",
  "72410 Mécaniciens/mécaniciennes et réparateurs/réparatrices de véhicules automobiles, de camions et d'autobus",
  "72411 Techniciens/techniciennes en collision, en carrosserie, en peinture et en glace de véhicule automobile et les estimateurs/estimatrices de dommages",
  "72420 Installateurs/installatrices de br├╗leurs à l'huile et à combustibles solides",
  "72421 Réparateurs/réparatrices et préposés/préposées à l'entretien d'appareils",
  "72422 ├ëlectromécaniciens/électromécaniciennes",
  "72423 Mécaniciens/mécaniciennes de motocyclettes, de véhicules tout-terrain et personnel mécanicien assimilé",
  "72429 Autres réparateurs/réparatrices de petits moteurs et de petits équipements",
  "72500 Grutiers/grutières",
  "72501 Foreurs/foreuses de puits d'eau",
  "72600 Pilotes, navigateurs/navigatrices et instructeurs/instructrices de pilotage du transport aérien",
  "72601 Contrôleurs aériens/contrôleuses aériennes et personnel assimilé",
  "72602 Officiers/officières de pont du transport par voies navigables",
  "72603 Officiers mécaniciens/officières mécaniciennes du transport par voies navigables",
  "72604 Contrôleurs/contrôleuses de la circulation ferroviaire et régulateurs/régulatrices de la circulation maritime",
  "72999 Autres métiers techniques et personnel assimilé",
  "73100 Finisseurs/finisseuses de béton",
  "73101 Carreleurs/carreleuses",
  "73102 Plâtriers/plâtrières, poseurs/poseuses et finisseurs/finisseuses de systèmes intérieurs et latteurs/latteuses",
  "73110 Couvreurs/couvreuses et poseurs/poseuses de bardeaux",
  "73111 Vitriers/vitrières",
  "73112 Peintres et décorateurs/décoratrices (sauf décorateurs/décoratrices d'intérieur)",
  "73113 Poseurs/poseuses de rev├¬tements d'intérieur",
  "73200 Personnel d'installation, d'entretien et de réparation d'équipement résidentiel et commercial",
  "73201 Préposés à l'entretien général et surintendants/surintendantes",
  "73202 Fumigateurs/fumigatrices et préposés/préposées au contrôle de la vermine",
  "73209 Autres réparateurs/réparatrices et préposés/préposées à l'entretien",
  "73300 Conducteurs/conductrices de camions de transport",
  "73301 Conducteurs/conductrices d'autobus et opérateurs/opératrices de métro et autres transports en commun",
  "73310 Mécaniciens/mécaniciennes de locomotive et de cour de triage",
  "73311 Chefs de train et serre-freins",
  "73400 Conducteurs/conductrices d'équipement lourd",
  "73401 Opérateurs/opératrices de presses à imprimer",
  "73402 Foreurs/foreuses et dynamiteurs/dynamiteuses de mines à ciel ouvert, de carrières et de chantiers de construction",
  "74100 Trieurs/trieuses de courrier et de colis et professions connexes",
  "74101 Facteurs/factrices",
  "74102 Messagers/messagères",
  "74200 Ouvriers/ouvrières de gares de triage et à l'entretien de la voie ferrée",
  "74201 Matelots de pont et matelots de salle des machines du transport par voies navigables",
  "74202 Agents/agentes de piste dans le transport aérien",
  "74203 Préposés/préposées à la pose et à l'entretien des pièces mécaniques d'automobiles et de camions et équipements lourds",
  "74204 Personnel d'entretien des services publics",
  "74205 Conducteurs/conductrices de machinerie d'entretien public et personnel assimilé",
  "75100 Débardeurs/débardeuses",
  "75101 Manutentionnaires",
  "75110 Aides de soutien des métiers et manoeuvres en construction",
  "75119 Autres manoeuvres et aides de soutien de métiers",
  "75200 Chauffeurs/chauffeuses de taxi, chauffeurs/chauffeuses de limousine et chauffeurs/chauffeuses",
  "75201 Chauffeurs-livreurs/chauffeuses-livreuses de services de livraison et distributeurs/distributrices porte-à-porte",
  "75210 Opérateurs/opératrices de bateau à moteur, de bac à c├óble et personnel assimilé",
  "75211 Manoeuvres dans le transport ferroviaire et routier",
  "75212 Manoeuvres à l'entretien des travaux publics",
  "80010 Directeurs/directrices de l'exploitation des ressources naturelles et de la p├¬che",
  "80020 Gestionnaires en agriculture",
  "80021 Gestionnaires en horticulture",
  "80022 Gestionnaires en aquaculture",
  "82010 Surveillants/surveillantes de l'exploitation forestière",
  "82020 Surveillants/surveillantes de l'exploitation des mines et des carrières",
  "82021 Entrepreneurs/entrepreneuses et surveillants/surveillantes du forage et des services reliés à l'extraction de pétrole et de gaz",
  "82030 Entrepreneurs/entrepreneuses de services agricoles et surveillants/surveillantes d'exploitations agricoles",
  "82031 Entrepreneurs/entrepreneuses et superviseurs/superviseures des services de l'aménagement paysager, de l'entretien des terrains et de l'horticulture",
  "83100 Mineurs/mineuses d'extraction et de préparation, mines souterraines",
  "83101 Foreurs/foreuses et personnel de mise à l'essai et des autres services reliés à l'extraction de pétrole et de gaz",
  "83110 Conducteurs/conductrices de machines d'abattage d'arbres",
  "83120 Capitaines et officiers/officières de bâtiments de p├¬che",
  "83121 P├¬cheurs indépendants/p├¬cheuses indépendantes",
  "84100 Travailleurs/travailleuses d'entretien et de soutien des mines souterraines",
  "84101 Travailleurs/travailleuses du forage et de l'entretien des puits de pétrole et de gaz et personnel assimilé",
  "84110 Opérateurs/opératrices de scies à chaîne et d'engins de débardage",
  "84111 Ouvriers/ouvrières en sylviculture et en exploitation forestière",
  "84120 Ouvriers spécialisés/ouvrières spécialisées dans l'élevage et opérateurs/opératrices de machineries agricoles",
  "84121 Matelots de pont sur les bâtiments de p├¬che",
  "85100 Manoeuvres aux soins du bétail",
  "85101 Manoeuvres à la récolte",
  "85102 Manoeuvres de l'aquaculture et de la mariculture",
  "85103 Manoeuvres de pépinières et de serres",
  "85104 Trappeurs/trappeuses et chasseurs/chasseuses",
  "85110 Manoeuvres des mines",
  "85111 Manoeuvres de forage et d'entretien des puits de pétrole et de gaz, et personnel assimilé",
  "85120 Manoeuvres de l'exploitation forestière",
  "85121 Manoeuvres en aménagement paysager et en entretien des terrains",
  "90010 Directeurs/directrices de la fabrication",
  "90011 Directeurs/directrices des services d'utilité publique",
  "92010 Surveillants/surveillantes dans la transformation des métaux et des minerais",
  "92011 Surveillants/surveillantes dans le raffinage du pétrole, dans le traitement du gaz et des produits chimiques et dans les services d'utilité publique",
  "92012 Surveillants/surveillantes dans la transformation des aliments et des boissons",
  "92013 Surveillants/surveillantes dans la fabrication de produits en caoutchouc et en plastique",
  "92014 Surveillants/surveillantes dans la transformation des produits forestiers",
  "92015 Surveillants/surveillantes dans la transformation et la fabrication de produits textiles, de tissus, de fourrure et de cuir",
  "92020 Surveillants/surveillantes dans la fabrication de véhicules automobiles",
  "92021 Surveillants/surveillantes dans la fabrication de matériel électronique et d'appareils électriques",
  "92022 Surveillants/surveillantes dans la fabrication de meubles et d'accessoires",
  "92023 Surveillants/surveillantes dans la fabrication d'autres produits métalliques et de pièces mécaniques",
  "92024 Surveillants/surveillantes dans la fabrication et le montage de produits divers",
  "92100 Mécaniciens/mécaniciennes de centrales et opérateurs/opératrices de réseaux électriques",
  "92101 Opérateurs/opératrices d'installations du traitement de l'eau et des déchets",
  "93100 Opérateurs/opératrices de poste central de contrôle et de conduite de procédés industriels dans le traitement des métaux et des minerais",
  "93101 Opérateurs/opératrices de salle de commande centrale et de conduite de procédés industriels dans le raffinage du pétrole et le traitement du gaz et des produits chimiques",
  "93102 Opérateurs/opératrices au contrôle de la réduction en pâte des pâtes et papiers, de la fabrication du papier et du couchage",
  "93200 Monteurs/monteuses d'aéronefs et contrôleurs/contrôleuses de montage d'aéronefs",
  "94100 Opérateurs/opératrices de machines dans le traitement des métaux et des minerais",
  "94101 Ouvriers/ouvrières de fonderies",
  "94102 Opérateurs/opératrices de machines à former et à finir le verre et coupeurs/coupeuses de verre",
  "94103 Opérateurs/opératrices de machines dans le fa├ºonnage et la finition des produits en béton, en argile ou en pierre",
  "94104 Contrôleurs/contrôleuses et essayeurs/essayeuses dans la transformation des métaux et des minerais",
  "94105 Opérateurs/opératrices de machines à forger et à travailler les métaux",
  "94106 Opérateurs/opératrices de machines d'usinage",
  "94107 Opérateurs/opératrices de machines d'autres produits métalliques",
  "94110 Opérateurs/opératrices d'installations de traitement des produits chimiques",
  "94111 Opérateurs/opératrices de machines de traitement des matières plastiques",
  "94112 Opérateurs/opératrices de machines de transformation du caoutchouc et personnel assimilé",
  "94120 Opérateurs/opératrices de machines à scier dans les scieries",
  "94121 Opérateurs/opératrices de machines dans la fabrication et la finition du papier dans les usines de pâte à papier",
  "94122 Opérateurs/opératrices de machines à fa├ºonner le papier",
  "94123 Classeurs/classeuses de bois d'oeuvre et autres vérificateurs/vérificatrices et classeurs/classeuses dans la transformation du bois",
  "94124 Opérateurs/opératrices de machines à travailler le bois",
  "94129 Autres opérateurs/opératrices de machines dans la transformation du bois",
  "94130 Opérateurs/opératrices de machines et travailleurs/travailleuses de traitement des fibres et des fils textiles, du cuir et des peaux",
  "94131 Tisseurs/tisseuses, tricoteurs/tricoteuses et autres opérateurs/opératrices de machines textiles",
  "94132 Opérateurs/opératrices de machines à coudre industrielles",
  "94133 Contrôleurs/contrôleuses et trieurs/trieuses dans la fabrication de produits textiles, de tissus, de fourrure et de cuir",
  "94140 Opérateurs/opératrices de machines et de procédés industriels dans la transformation des aliments et des boissons",
  "94141 Bouchers industriels/bouchères industrielles, dépeceurs-découpeurs/dépeceuses-découpeuses de viande, préparateurs/préparatrices de volaille et personnel assimilé",
  "94142 Ouvriers/ouvrières dans les usines de transformation du poisson et de fruits de mer",
  "94143 ├ëchantillonneurs/échantillonneuses et trieurs/trieuses dans la transformation des aliments et des boissons",
  "94150 Opérateurs/opératrices d'équipement d'impression sans plaque",
  "94151 Photograveurs-clicheurs/photograveuses-clicheuses, photograveurs-reporteurs/photograveuses-reporteuses et autre personnel de prépresse",
  "94152 Opérateurs/opératrices de machines à relier et de finition",
  "94153 Développeurs/développeuses de films et de photographies",
  "94200 Assembleurs/assembleuses, contrôleurs/contrôleuses et vérificateurs/vérificatrices de véhicules automobiles",
  "94201 Assembleurs/assembleuses, monteurs/monteuses, contrôleurs/contrôleuses et vérificateurs/vérificatrices de matériel électronique",
  "94202 Monteurs/monteuses et contrôleurs/contrôleuses dans la fabrication de matériel, d'appareils et d'accessoires électriques",
  "94203 Assembleurs/assembleuses, monteurs/monteuses et contrôleurs/contrôleuses dans la fabrication de transformateurs et de moteurs électriques industriels",
  "94204 Monteurs/monteuses et contrôleurs/contrôleuses de matériel mécanique",
  "94205 Opérateurs/opératrices de machines et contrôleurs/contrôleuses dans la fabrication d'appareils électriques",
  "94210 Monteurs/monteuses, finisseurs/finisseuses, restaurateurs/restauratrices et contrôleurs/contrôleuses de meubles et d'accessoires",
  "94211 Monteurs/monteuses et contrôleurs/contrôleuses d'autres produits en bois",
  "94212 Assembleurs/assembleuses, finisseurs/finisseuses et contrôleurs/contrôleuses de produits en plastique",
  "94213 Peintres, enduiseurs/enduiseuses et opérateurs/opératrices de procédés dans le finissage du métal - secteur industriel",
  "94219 Monteurs/monteuses, finisseurs/finisseuses et contrôleurs/contrôleuses de produits divers",
  "95100 Manoeuvres dans le traitement des métaux et des minerais",
  "95101 Manoeuvres en métallurgie",
  "95102 Manoeuvres dans le traitement des produits chimiques et les services d'utilité publique",
  "95103 Manoeuvres dans le traitement des pâtes et papiers et la transformation du bois",
  "95104 Manoeuvres dans la fabrication des produits en caoutchouc et en plastique",
  "95105 Manoeuvres dans la fabrication et la coupe des produits du textile",
  "95106 Manoeuvres dans la transformation des aliments et des boissons",
  "95107 Manoeuvres dans la transformation du poisson et des fruits de mer",
  "95109 Autres manoeuvres des services de transformation, de fabrication et d'utilité publique"
];
